server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432/product_db}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: PRODUCT-SERVICE
  config:
    import:
      configserver:${CONFIG_SERVER_URL:http://localhost:9296}


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-43724657.okta.com/oauth2/default
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
#logging:
#  level:
#    org:
#      springframework: DEBUG
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

